name: Deploy

on:

  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check status
      run: echo 'Check if ready for deploy'
    - name: Deploy
      run: echo 'Deploy'
    - name: Post Deploy
      run: echo 'Post deploy checks'