name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
    - name: Check status
      run: echo ${{ github.event }}
    - name: Deploy
      run: echo 'Deploy'
    - name: Post Deploy
      run: echo ${{ github.event_name }}
